# Generated by Django 6.0.6 on 2026-06-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_order_razorpay_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
