# Generated by Django 6.0.6 on 2026-06-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_customerprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.IntegerField(
                default=0, help_text="Current available inventory"
            ),
        ),
    ]
