# Generated by Django 6.0.6 on 2026-06-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_product_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., SUMMER20", max_length=50, unique=True
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage (%)"),
                            ("flat", "Flat Amount (₹)"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Enter 20 for 20%, or 100.00 for ₹100 off",
                        max_digits=10,
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
                ("max_uses", models.IntegerField(default=100)),
                ("current_uses", models.IntegerField(default=0)),
            ],
        ),
    ]
