# Generated by Django 6.0.6 on 2026-06-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
