# Generated by Django 5.2.15 on 2026-06-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_order_shipping_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="guest_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
