# Generated by Django 5.2.15 on 2026-06-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_order_guest_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="receiver_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="receiver_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
